name: ActionLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  actionlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install actionlint
        run: npm install -g actionlint

      - name: Run ActionLint
        run: actionlint .github/workflows/*.yml
      - uses: devops-actions/actionlint@<VERSION OR SHA>
        continue-on-error: true
        id: action-lint
