name: OpenSSF Scorecard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scorecard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add steps to run OpenSSF Scorecard
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v1
